#' Show Functional Antennal Lobe
#' 
#' Show the functional antennal lobe responded to a single odor.
#' 
#' normalized response data across receptors to a given odor can obtained using
#' \code{\link{findRespNorm}}.  The function then maps the receptor responses
#' onto the respective glomeruli, resulting in a colored map of the antennal
#' lobe. Default colors range from red (most inhibitory response) over white
#' (around baseline) to blue (most excitatory response), see
#' \code{\link{DoORColmap}}.
#' 
#' The three-dimensional antennal lobe is displayed as four two-dimensional
#' slices at different z-positions.  Light grey glomeruli shine through from
#' other slices (background, BG).  Unmapped (UM) glomeruli are painted in dark
#' grey - in these cases the receptor-glomerulus mapping is currently unknown.
#' Grey indicates NA, i.e. that no measurements are available for the
#' respective glomerulus (receptor).
#' 
#' @param response.data a data frame; normalized response data across
#' receptors, which is generated by \code{\link{findRespNorm}}.
#' @param tag.ALimage character string; Default is "Glomerulus", the options
#' include "Ors" and "ORN".
#' @param main title of figure; Default is NULL.
#' @param col.extrem character vector; The default is c("blue", "red"), i.e.
#' the color scale ranges from blue to red
#' @param ind.panels logical; if \code{TRUE}, the indicated panels are shown on
#' the right side.
#' @param DoOR.mappings a data frame; maps receptor to sensillum, receptor neuron and
#' glomerulus.
#' @param AL256 a data frame; which contains pixel values to code the graphic
#' antennal lobe.
#' @author Shouwen Ma <\email{shouwen.ma@@uni-konstanz.de}>
#' @seealso \code{\link{findRespNorm}},\code{\link{CreateDatabase}}
#' @keywords hplot
#' @examples
#' 
#' library(DoOR.data)
#' library(DoOR.function)
#' loadRD()
#' data(response.range)
#' data(DoOR.mappings)
#' data(AL256)
#' cas<-c("628-63-7")
#' RP.PAcE<-findRespNorm(cas,responseMatrix= response.matrix)
#' ALimage(RP.PAcE, main = "PAcE", DoOR.mappings = DoOR.mappings, AL256 = AL256)
#' 
ALimage <- function (response.data, 
                  	 tag.ALimage =  default.val("tag.ALimage"), 
                  	 main = default.val("main"),
                  	 col.extrem = default.val("col.extrem"),
                  	 ind.panels = default.val("ind.panels"),
                  	 DoOR.mappings = default.val("DoOR.mappings"), 
                  	 AL256 = default.val("AL256") ) {

  # rotate the AL256 pix matrix
  transg <- matrix(c(t(AL256)[, c(dim(t(AL256))[2]:1)]), nrow = dim(t(AL256))[1])

  # find the attribute variables in the AL256 matrix; the variables define the positions of glomeruli.
  levg <- levels(factor(transg))

  # extract a subset that contains a complete "Code" column from "DoOR.mappings"
  mappings.subset         <- subset(DoOR.mappings, !is.na(Code))
  match_receptor          <- na.omit(match(response.data[, "ORs"], mappings.subset[, "receptor"]))
  rcode                   <- mappings.subset[match_receptor, "code"]
  available_receptor      <- na.omit(match(mappings.subset[, "code"], rcode))
  not_available_receptor  <- mappings.subset[attr(available_receptor, "na.action"), "Code"]

  # set background to NA
  transg[which(transg == 255)] <- NA
  
  OR.val    <- response.data[-attr(match_receptor, "na.action"), "Response"]
  range.RD  <- range(OR.val, na.rm = TRUE)

  # if the range of response data exceeds the boundaries [-1, 1], then normalize the data to the range [-1, 1]
  if (range.RD[1] < (-1))
    OR.val <- OR.val/abs(range.RD[1])

  if (range.RD[1] > (1))
    OR.val = OR.val/abs(range.RD[2])

  # background gray
  colset <- rep("#DEDEDE", length = length(levels(factor(transg))))
  mycol  <- colset

  # define the colors of glomeruli 
  mycolset <- DoORColmap(OR.val, col.extrem = col.extrem)

  # find the glomeruli with missing response values; 
  # the glomeruli will be marked as gray color "#B8B8B8".
  fna <- which(is.na(mycolset))
  if (!is.na(fna[1])) 
    mycolset[fna] <- "#B8B8B8"

  # find the unassigned glomeruli; 
  # these glomeruli will be marked as color "#575757".
  mycol[(rcode)] <- mycolset
  mycol[(not_available_receptor)] <- "#575757"

  # show the color palettes
  if (ind.panels == TRUE) {
    layout(matrix(c(0, 0, 3, 0,
                    0, 1, 3, 0,
                    0, 1, 2, 0,
                    0, 0, 2, 0), 
                  nc = 4, byrow = TRUE),
           height = c(0.1, 1, 1, 0.1), 
           width = c(lcm(1), 10, 1, lcm(1)))
    par(mar = c(2, 2, 2, 2))

    # show the figure with defined colors
    image(transg, col = mycol, axes = FALSE)
    frame.transg <- dim(transg)
    # show the names of glomeruli on the AL
    for (i in 1:dim(mappings.subset)[1]) {
      text(x = mappings.subset[i, "x"]/frame.transg[1], y = (frame.transg[2] - mappings.subset[i, "y"])/frame.transg[2], mappings.subset[i, tag.ALimage])
    }
    if (!is.null(main))
      title(main, cex.main = 2)
  
    # show the color palette
    par(mar = c(4, 2, 2, 1), las = 2)
  
    cols <- DoORColmap(x=null,color.scale=TRUE)
    image(t(as.matrix(1:255)), col = cols, axes = FALSE)
    axis(4, labels = c("-1", "0", "1"), at = c(0, 85/255, 1))
    par(mar = c(4, 2, 5, 1), las = 2)
  
    # show palette with gray values
    image(t(as.matrix(1:3)), col = c("#DEDEDE", "#B8B8B8","#575757"), axes = FALSE)
    text(x = 0.2, y = c(1, 0.5, 0), c("UM", "NA", "BG"))

  } else { # end if (ind.panels == TRUE)
      par(mar = c(2, 2, 2, 0.5))
      image(transg, col = mycol, axes = FALSE)
      frame.transg <- dim(transg)
      for (i in 1:dim(mappings.subset)[1]){
        text(x = mappings.subset[i, "x"]/frame.transg[1], y = (frame.transg[2] - 
        mappings.subset[i, "y"])/frame.transg[2], mappings.subset[i, tag.ALimage])
      }
      if (!is.null(main)) 
          title(main, cex.main = 2)
  }
}
