ALimage <-
function (response.data, 
		tag.ALimage =  default.val("tag.ALimage"), 
		main = default.val("main"),
		col.extrem = default.val("col.extrem"),
		ind.panels = default.val("ind.panels"),
		OGN = default.val("OGN"), 
		AL256 = default.val("AL256") ) 

# part of the DoOR package: (c) 2009 C. Giovanni Galizia, Daniel Muench, Martin Strauch, Anja Nissler, Shouwen Ma
# Neurobiology, University of Konstanz, Germany


# ALimage.R:
############

# draws an antennal lobe image (colored such as to show the response to an odorant)





# paramters:
#############

#  response.data : a data frame; normalized response data across receptors, which is generated by findRespNorm.
#  tag.ALimage 	 : character string; what should the labels on the glomeruli contain? default is "Glomerulus", the options include "Ors" and "ORN"
#  main 	 : title for the figure; Default is NULL.
#  col.extrem 	 : character vector;  The default is c("blue", "red"), i.e. the color scale ranges from blue to red 
#  ind.panels 	 : logical; if TRUE, the indicated panels are shown on the right side
#  OGN 		 : a data frame; maps receptor to sensillum, receptor neuron and glomerulus.
#  AL256 	 : a data frame; which contains pixel values; the (empty) antennal lobe image

{

    ## main program starts here
    
    # rotate the AL256 pix matrix
    transg <- matrix(c(t(AL256)[, c(dim(t(AL256))[2]:1)]), nrow = dim(t(AL256))[1])

    # find the attribute variables in the AL256 matrix; the variables define the positions of glomeruli.
    levg <- levels(factor(transg))

    # extract a subset that contains a complete "Code" column from "OGN"
    subsetOGN 		   <- subset(OGN, !is.na(Code))
    match_receptor 	   <- na.omit(match(response.data[, "ORs"], subsetOGN[, "Receptor"]))
    rcode 	    	   <- subsetOGN[match_receptor, "Code"]
    available_receptor 	   <- na.omit(match(subsetOGN[, "Code"], rcode))
    not_available_receptor <- subsetOGN[attr(available_receptor, "na.action"), "Code"]

    # set background to NA
    transg[which(transg == 255)] <- NA
    
    OR.val 	<- response.data[-attr(match_receptor, "na.action"), "Response"]
    range.RD 	<- range(OR.val, na.rm = TRUE)

    # if the range of response data exceeds the boundaries [-1, 1], then normalize the data to the range [-1, 1]
    if (range.RD[1] < (-1))
    {
         OR.val <- OR.val/abs(range.RD[1])
    }
    if (range.RD[1] > (1))
    { 
         OR.val = OR.val/abs(range.RD[2])
    }

    # background gray
    colset <- rep("#DEDEDE", length = length(levels(factor(transg))))
    mycol  <- colset

    # define the colors of glomeruli 
    mycolset <- DoORColmap(OR.val, col.extrem = col.extrem)

    # find the glomeruli with missing response values; 
    # the glomeruli will be marked as gray color "#B8B8B8".
    fna <- which(is.na(mycolset))
    if (!is.na(fna[1])) { mycolset[fna] <- "#B8B8B8" }

    # find the unassigned glomeruli; 
    # these glomeruli will be marked as color "#575757".
    mycol[(rcode)] <- mycolset
    mycol[(not_available_receptor)] <- "#575757"

    # show the color palettes
    if (ind.panels == TRUE)
    {
        layout(matrix(c(0, 0, 3, 0, 
			0, 1, 3, 0, 
			0, 1, 2, 0, 
			0, 0, 2, 0), nc = 4, byrow = TRUE), 
		height = c(0.1, 1, 1, 0.1), width = c(lcm(1), 10, 1, lcm(1)))
        par(mar = c(2, 2, 2, 2))

	# show the figure with defined colors
        image(transg, col = mycol, axes = FALSE)
        frame.transg <- dim(transg)
	# show the names of glomeruli on the AL
        for (i in 1:dim(subsetOGN)[1]) 
        {
            text(x = subsetOGN[i, "x"]/frame.transg[1], y = (frame.transg[2] - 
                subsetOGN[i, "y"])/frame.transg[2], subsetOGN[i, tag.ALimage])
        }
        if (!is.null(main)) { title(main, cex.main = 2) }
	
	# show the color palette
        par(mar = c(4, 2, 2, 1), las = 2)

 	cols <- DoORColmap(x=null,color.scale=TRUE)
        image(t(as.matrix(1:255)), col = cols, axes = FALSE)
        axis(4, labels = c("-1", "0", "1"), at = c(0, 85/255, 1))
        par(mar = c(4, 2, 5, 1), las = 2)
	
        # show palette with gray values
        image(t(as.matrix(1:3)), col = c("#DEDEDE", "#B8B8B8","#575757"), axes = FALSE)
        text(x = 0.2, y = c(1, 0.5, 0), c("UM", "NA", "BG"))

    } # end if (ind.panels == TRUE)
    else 
    {
        par(mar = c(2, 2, 2, 0.5))
        image(transg, col = mycol, axes = FALSE)
        frame.transg <- dim(transg)
        for (i in 1:dim(subsetOGN)[1]) 
	{
            text(x = subsetOGN[i, "x"]/frame.transg[1], y = (frame.transg[2] - 
                subsetOGN[i, "y"])/frame.transg[2], subsetOGN[i, tag.ALimage])
        }
        if (!is.null(main)) 
            title(main, cex.main = 2)
    }

}
