#' Bar Plot of Responses of given receptor
#' 
#' Create a horizontal bar plot and show the response profile of all commented
#' odor receptors to odor(s).
#' 
#' This function is used to visualize the response profile of all commented
#' odor receptors to odors. For \code{DoORplot_compareReceptors}, the given data should be
#' generated by \code{\link{findRespNorm}} or the columns of data must be name
#' of odor receptors, InChIKey and normalized response value. The color bar
#' from green to magenta indicates that the response intensity from most
#' inhibitory to most excitatory. White area between green and magenta
#' indicates that the odor response is weak.
#' 
#' @param data data frame; containing the names of odorant receptors, InChIKey and normalized response values.
#' @param odor.data data frame; chemical data of odors.
#' \code{\link[DoOR.data]{odor}}
#' @param tag character string; default tag is the InChIKey.
#' @param name.title character string; the main title of plot. Dafaults to
#' "Chemical Responses Crossing Odor Receptors".
#' @param pic.height numeric; the height of the device; the default is 1296.
#' @param file.name character string; file name; if missing, the default file
#' name is "DoORplot_compareReceptors.pdf" or "DoORplot_compareReceptors.jpeg"
#' @param cex.title numeric; the magnification to be used for main titles. The
#' default is 1.
#' @param x.range numeric vectors of length 2; giving the x coordinates ranges.
#' @param cex.axes numeric; the magnification to be used for axes. The default
#' is 1.
#' @param cex.tag numeric; the magnification to be used for tag. The default is
#' 1.
#' @param PDF logical; if \code{TRUE}, then the bar plot will be saved as PDF
#' file. The default is \code{FALSE}.
#' @param JPEG logical; if \code{TRUE}, then the bar plot will be saved as JPEG
#' file. The default is \code{FALSE}.
#' @param pic.width numeric; the width of the device; the default is 864.
#' @param point.size numeric; pointsize of plotted text; one point is
#' approximately one pixel, and the default is 17.
#' @param col.extrem a two characters vector; coding the colour of each end.
#' The default is c("blue", "red").
#' @author Shouwen Ma <\email{shouwen.ma@@uni-konstanz.de}>
#' @export
#' @seealso \code{\link{findRespNorm}}
#' @keywords iplot
#' @examples
#' 
#' library(DoOR.data)
#' loadRD()
#' data(odor)
#' odors <- c("LRHPLDYGYMQRHN-UHFFFAOYSA-N", "MLFHJEHSLIIPHL-UHFFFAOYSA-N", "XBDQKXXYIPTUBI-UHFFFAOYSA-N")
#' result2<-findRespNorm(odors, responseMatrix = response.matrix)
#' DoORplot_compareReceptors(result2,odor.data=odor,tag="Name",PDF=TRUE)
#' 
DoORplot_compareReceptors <-
function(data, odor.data,
		tag = default.val("tag"),
		name.title, pic.height, file.name,
		cex.title = 1, x.range, cex.axes = 1, cex.tag = 1, PDF = FALSE, JPEG = FALSE, pic.width = 864, point.size = 17,
		col.extrem = default.val("col.extrem") ) 

# part of the DoOR package: (c) 2009 C. Giovanni Galizia, Daniel Muench, Martin Strauch, Anja Nissler, Shouwen Ma
# Neurobiology, University of Konstanz, Germany


# Plot Receptors.R
####################

# Bar plot showing the response profile of all odorant receptors to an odor/several odors




# parameters:
##############

#  data 	: data frame; containing the names of odorant receptors, InChIKey and normalized response values. 
#  odor.data 	: data frame; chemical data of odors. 
#  tag 		: character string; default tag is the InChIKey. 
#  name.title 	: character string; the main title of plot. Dafaults to "Chemical Responses Crossing Odor Receptors". 
#  cex.title 	: numeric; the magnification to be used for main titles. The default is 1. 
#  x.range 	: numeric vectors of length 2; giving the x coordinates ranges. 
#  cex.axes 	: numeric; the magnification to be used for axes. The default is 1. 
#  cex.tag 	: numeric; the magnification to be used for tag. The default is 1. 
#  PDF 		: logical; if TRUE, then the bar plot will be saved as PDF file. The default is FALSE.
#  JPEG 	: logical; if TRUE, then the bar plot will be saved as JPEG file. The default is FALSE.  
#  pic.width 	: numeric; the width of the device; the default is 864. 
#  pic.height 	: numeric; the height of the device; the default is 1296. 
#  point.size 	: numeric; pointsize of plotted text; one point is approximately one pixel, and the default is 17. 
#  file.name 	: character string; file name; if missing, the default file name is "DoORplot_compareReceptors.pdf" or "DoORplot_compareReceptors.jpeg" 
#  col.extrem 	: a two characters vector; The default is c("blue", "red"), indicating a color scale ranging from blue to red.

{

	# plotting function for ramp colors
	plot.subfun <- function(data,x.range,cex.tag,cex.axes,cols,name.title,cex.title) 
	{
		layout(matrix(c(
			0,0,0,0,
			0,2,0,0,
			0,2,1,0,
			0,0,0,0),nc=4, byrow = TRUE),
			height = c(0.1, 1, 1, 0.1),
			width = c(0.5, 8,  1.6, 0.5))

		par(mar=c(4, 4, 2, 2))
		image(t(as.matrix(1:255)),col=cols,axes = FALSE)
		axis(4,labels=c("-1","0","1"),at=c(0,85/255,1),las=2)

		par(mar=c(4, 4, 2, 2))	
		colset 	<- DoORColmap(data, col.extrem = col.extrem)
		op 	<- par(mar=c(5,11, 4, 1.7), las=2,cex.axis=cex.axes)
		barplot(data,space=0.5,horiz=TRUE,xlim = x.range,cex.names=cex.tag,col=colset,axes=FALSE)
		axis(1,las=1)
		title(name.title,cex.main=cex.title)
	}




        #########################################################################################################
	## main programme starts here
	
	cols <- DoORColmap(x=null,color.scale=TRUE)

	rowCount 	     <- 42			# number of bars for a page
	response_data_vector <- data[,"Response"]
	names(response_data_vector) <- paste(data[,"ORs"],":",data[,"Odor"],sep="  ")
	 
	if (tag=="Name") 
	{
		matchOdor <- match(data[,"Odor"], odor.data$InChIKey)
		odname 	  <- odor.data$Name[matchOdor]
		names(response_data_vector) <- paste(data[,"ORs"],":",odname,sep="  ")
	}
	if (missing(x.range)) 	 { x.range <- c(min(response_data_vector,na.rm=TRUE),max(response_data_vector,na.rm=TRUE)) }
	if (missing(name.title)) { name.title = paste("Chemical Responses Crossing Odor Receptors") }

	len_data_vector <- length(na.omit(response_data_vector))
	if (missing(pic.height)) { pic.height <- (pic.width*len_data_vector*0.44)/42 }

	if (JPEG==TRUE) 
	{
		if (missing(file.name)) { jpeg("DoORplot_compareReceptors.jpeg",width=pic.width, height=pic.height,pointsize=point.size) }
		else 			{ jpeg(file.name,width=pic.width, height=pic.height,pointsize=point.size) }
		rev_response_data_vector <- rev(response_data_vector)
		plot.subfun(data=rev_response_data_vector,x.range,cex.axes,cex.tag,cols,name.title,cex.title)
		dev.off()
	}

	else {
		n_page <- 0:floor(length(response_data_vector)/rowCount)
		if (PDF==TRUE)	
		{
			if (missing(file.name)) { pdf("DoORplot_compareReceptors.pdf",width=6, height=8) }
			else 			{ pdf(file.name,width=6, height=8) }
		}
		for (i in n_page) 	
		{
			n_bar <- (i*rowCount+1):(i*rowCount+rowCount)
			response_data_vector_i 	 <- response_data_vector[n_bar]
			rev_response_data_vector <- rev(response_data_vector_i)
			if (PDF==TRUE) { plot.subfun(data=rev_response_data_vector,x.range,cex.axes,cex.tag,cols,name.title,cex.title) }
			else
			{
				X11()
				plot.subfun(data=rev_response_data_vector,x.range,cex.axes,cex.tag,cols,name.title,cex.title)
			}
		}
		if (PDF==TRUE) { dev.off() }


	} # END else
}
